name: Build resymgen
description: Build and install resymgen (release profile and tests) or retrieve it from cache
runs:
  using: composite
  steps:
    - name: Check cache
      id: cache-lookup
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/resymgen
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: cache-v3_${{ runner.os }}-${{ hashFiles('Cargo.toml') }}-${{ hashFiles('src/**') }}
    - name: Build resymgen
      run: cargo build --release --verbose
      shell: bash
      if: steps.cache-lookup.outputs.cache-hit != 'true'
    - name: Build tests
      run: cargo build --tests --verbose
      shell: bash
      if: steps.cache-lookup.outputs.cache-hit != 'true'
    - name: Install
      run: cargo install --path .
      shell: bash
      if: steps.cache-lookup.outputs.cache-hit != 'true'
