name: Check resymgen

on:
  pull_request:
    paths:
      - 'src/**.rs'
      - 'Cargo.toml'
    branches:
      - master
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Format check
        run: cargo fmt --verbose -- --check
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build-resymgen
      - name: Test
        run: cargo test --verbose
  clippy-check:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Clippy
        run: rustup component add clippy
      - name: Run Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
